name: Mac_CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths: 
    - '**.pl'
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Install and setup Perl
      run: brew install perl
    
    # Runs a single command using the runners shell
    - name: Check perl version
      run: perl -v

    - name: Install Dependencies
      run: |
        curl -L https://cpanmin.us | perl - File::Find::Rule
        curl -L https://cpanmin.us | perl - MIME::Base32
        curl -L https://cpanmin.us | perl - Readonly
        curl -L https://cpanmin.us | perl - Convert::Base85
  
    # Github action doesn't support perl shell (Duh!). Hence created a seperate script which will run all other scripts in repo.
    - name: Run All the scripts
      run: |
        perl run_all_scripts.pl
