name: Windows_CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths: 
    - '**.pl'
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Install and setup Perl
      run: |
          choco install strawberryperl
          echo "##[add-path]C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin"
    
    # Runs a single command using the runners shell
    - name: Check perl version
      run: perl -v

    - name: Install Dependencies
      run: |
        cpanm File::Find::Rule
        cpanm MIME::Base32
        cpanm Convert::Base85
        cpanm Readonly
  
    # Github action doesn't support perl shell (Duh!). Hence created a seperate script which will run all other scripts in repo.
    - name: Run All the scripts
      run: |
        perl run_all_scripts.pl
